pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Git checkOut') {
            steps {
                git branch: '*/main', url: 'https://github.com/MahbubAhmedTonmoy/jenkins-Learn-Dotnet-core-app.git'
            }
        }
        stage('Restore packages') {
            steps {
                bat "dotnet restore hello world app\\hello world app\\hello world app.csproj"
            }
        }

        stage('Clean') {
            steps {
                 bat "dotnet clean hello world app\\hello world app\\hello world app.csproj"
            }
        }
        stage('Build') {
            steps {
                bat "dotnet build hello world app\\hello world app\\hello world app.csproj --configuration Release"
            }
        }
        stage('Publish'){
            steps{
            bat "dotnet publish hello world app\\hello world app\\hello world app.csproj"
            }
        }
        stage('Run'){
            steps{
            bat "dotnet run hello world app\\hello world app\\hello world app.csproj"
            }
        }
    }
}